<script setup lang="ts">
import { ref } from 'vue'; import { ElMessage } from 'element-plus'; import ToolPageHeader from '@/components/tool/ToolPageHeader.vue'; import ToolDocumentation from '@/components/tool/ToolDocumentation.vue'; import { describeTime, parseTimestamp } from '../lib/timestamp'
const input=ref('');const result=ref<ReturnType<typeof describeTime>|null>(null);const error=ref('')
function convert(value=input.value){try{error.value='';result.value=describeTime(parseTimestamp(value))}catch(e){result.value=null;error.value=e instanceof Error?e.message:'转换失败'}}
function useNow(){input.value=String(Date.now());convert()}
async function copy(value:string|number){await navigator.clipboard.writeText(String(value));ElMessage.success('已复制')}
const docs=[{title:'自动识别',content:'10 位及以下纯数字按秒处理，13 位数字按毫秒处理，也支持 ISO 8601 等日期文本。'},{title:'时区说明',content:'ISO 时间统一使用 UTC，本地时间使用当前浏览器的系统时区。'}]
</script>
<template><div class="sr-page"><ToolPageHeader category="日期时间" title="时间戳转换" description="在秒、毫秒、ISO 时间和本地时间之间转换。" :tags="['时间戳','时区']"/><section class="tool-box sr-panel"><label class="sr-tool-label">时间戳或日期</label><el-input v-model="input" placeholder="例如 1704067200 或 2024-01-01T00:00:00Z" @keyup.enter="convert()"/><div class="actions"><el-button class="sr-primary-button" type="primary" @click="convert()">开始转换</el-button><el-button @click="useNow">使用当前时间</el-button><el-button @click="input='';result=null;error=''">清空</el-button></div><p v-if="error" class="error">{{error}}</p></section><section v-if="result" class="result sr-panel"><h2>转换结果</h2><div v-for="[name,value] in [['秒级时间戳',result.seconds],['毫秒时间戳',result.milliseconds],['ISO 8601',result.iso],['本地时间',result.local]]" :key="name"><span>{{name}}</span><code>{{value}}</code><el-button text @click="copy(value)">复制</el-button></div></section><ToolDocumentation :sections="docs"/></div></template>
<style scoped lang="scss">.tool-box,.result{padding:20px}.tool-box .el-input{margin-top:9px}.actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}.error{color:#c43f3f}.result{margin-top:14px}.result h2{margin:0 0 12px;color:#218a5a;font-size:15px}.result div{display:grid;grid-template-columns:110px 1fr auto;align-items:center;gap:12px;padding:10px 0;border-bottom:1px solid var(--sr-border)}.result span{color:var(--sr-text-muted);font-size:13px}.result code{word-break:break-all}</style>
