<script setup lang="ts">
import {computed,ref} from 'vue';import ToolPageHeader from '@/components/tool/ToolPageHeader.vue';import ToolDocumentation from '@/components/tool/ToolDocumentation.vue';import {parseJwt,verifyHmacJwt,describeTimestamp} from '../lib/jwt'
const token=ref('');const secret=ref('');const parsed=ref<ReturnType<typeof parseJwt>|null>(null);const error=ref('');const verification=ref<{type:'success'|'error';message:string}|null>(null)
const timeFields=computed(()=>parsed.value?(['iat','nbf','exp'] as const).flatMap(key=>{const info=describeTimestamp(parsed.value?.payload[key]);return info?[{key,...info}]:[]}):[])
function parse(){try{error.value='';verification.value=null;parsed.value=parseJwt(token.value.trim())}catch(e){parsed.value=null;error.value=e instanceof Error?e.message:'无法解析 JWT'}}
async function verify(){try{const result=await verifyHmacJwt(token.value.trim(),secret.value);verification.value={type:'success',message:`签名验证通过：令牌内容与当前密钥匹配（密钥编码：${result.keyEncoding}）。`}}catch(e){verification.value={type:'error',message:e instanceof Error?e.message:'签名验证失败'}}}
const docs=[{title:'JWT 的三个部分',content:'JWT 由 Header、Payload 和 Signature 组成。前两部分只是 Base64URL 编码，任何人都能读取。'},{title:'解析不等于可信',content:'解析成功只说明格式正确。只有签名验证通过，并检查 exp、nbf 等声明后，才能进一步判断令牌是否可接受。'},{title:'密钥安全',content:'密钥仅存在当前页面内存中，不会保存或上传。不要在不可信设备粘贴生产环境密钥。'}]
</script>
<template><div class="sr-page"><ToolPageHeader category="安全与认证" title="JWT 解析" description="查看 JWT 声明，并使用 HMAC 密钥验证签名。" :tags="['JWT','认证']"/><section class="jwt sr-panel"><label>JWT Token<textarea v-model="token" spellcheck="false" placeholder="粘贴 eyJ... 格式的令牌"></textarea></label><div class="actions"><el-button class="sr-primary-button" type="primary" @click="parse">解析令牌</el-button><el-button @click="token='';secret='';parsed=null;error=''">清空</el-button></div><p v-if="error" class="error">{{error}}</p></section><template v-if="parsed"><div class="warning">解析成功不代表令牌可信，请继续验证签名并检查有效期。</div><section class="parts"><article class="sr-panel"><h2>Header</h2><pre>{{JSON.stringify(parsed.header,null,2)}}</pre></article><article class="sr-panel"><h2>Payload</h2><pre>{{JSON.stringify(parsed.payload,null,2)}}</pre></article></section><section v-if="timeFields.length" class="times sr-panel"><h2>时间声明</h2><div v-for="field in timeFields" :key="field.key"><b>{{field.key}}</b><span>{{field.raw}}</span><span>{{field.local}}</span><span>{{field.iso}}</span></div></section><section class="verify sr-panel"><h2>HMAC 签名验证</h2><p>支持 HS256 / HS384 / HS512。密钥不会被保存。</p><el-input v-model="secret" type="password" show-password placeholder="输入 HMAC 密钥"/><el-button class="sr-primary-button" type="primary" :disabled="!secret" @click="verify">验证签名</el-button><div v-if="verification" :class="verification.type">{{verification.message}}</div></section></template><ToolDocumentation :sections="docs"/></div></template>
<style scoped lang="scss">.jwt{padding:20px}label{font-size:13px;font-weight:600}textarea{display:block;width:100%;height:140px;margin-top:8px;padding:14px;border:1px solid var(--sr-border);border-radius:var(--sr-radius-control);resize:vertical;background:var(--sr-surface-soft);color:var(--sr-text);font:13px/1.65 ui-monospace,monospace}textarea:focus{outline:0;border-color:var(--sr-blue)}.actions{display:flex;gap:8px;margin-top:14px}.error{color:#d34b4b}.warning{margin:14px 0;padding:13px;border-left:3px solid var(--sr-orange);background:var(--sr-orange-soft);font-size:13px}.parts{display:grid;grid-template-columns:1fr 1.6fr;gap:14px}.parts article,.times,.verify{padding:20px}.parts h2,.times h2,.verify h2{margin:0 0 13px;font-size:15px}.parts pre{max-height:330px;margin:0;overflow:auto;color:var(--sr-text);font:13px/1.65 ui-monospace,monospace;white-space:pre-wrap}.times{margin-top:14px}.times div{display:grid;grid-template-columns:55px 110px 1fr 1.5fr;gap:10px;padding:10px 0;border-bottom:1px solid var(--sr-border);font-size:12px}.verify{margin-top:14px}.verify p{color:var(--sr-text-muted);font-size:13px}.verify .el-input{max-width:500px;margin-right:8px}.success,.verify .error{margin-top:12px;padding:11px;background:var(--sr-blue-soft);color:var(--sr-blue);font-size:13px}.verify .error{background:#fdeaea;color:#c43f3f}@media(max-width:760px){.parts{grid-template-columns:1fr}.times div{grid-template-columns:45px 1fr}.times div span:last-child{grid-column:1/-1}.verify .el-input{margin:0 0 8px}}</style>
