<script setup lang="ts">
import { ref } from 'vue'; import { ElMessage } from 'element-plus'; import ToolPageHeader from '@/components/tool/ToolPageHeader.vue'; import ToolDocumentation from '@/components/tool/ToolDocumentation.vue'; import { hashText, type HashAlgorithm } from '../lib/hash'
const input=ref('');const algorithm=ref<HashAlgorithm>('sha256');const useHmac=ref(false);const key=ref('');const output=ref('');const error=ref('')
function run(){try{error.value='';if(useHmac.value&&!key.value)throw new Error('请输入 HMAC 密钥');output.value=hashText(input.value,algorithm.value,useHmac.value?key.value:undefined)}catch(e){output.value='';error.value=e instanceof Error?e.message:'计算失败'}}
async function copy(){await navigator.clipboard.writeText(output.value);ElMessage.success('结果已复制')}
const docs=[{title:'算法',content:'支持 MD5、SHA-1、SHA-256 和 SHA-512。MD5 与 SHA-1 仅适合兼容场景，不建议用于安全校验。'},{title:'HMAC',content:'HMAC 使用密钥对内容进行消息认证，密钥只保存在当前页面内存中。'}]
</script>
<template><div class="sr-page"><ToolPageHeader category="安全与认证" title="Hash / HMAC 计算" description="计算文本摘要或带密钥的 HMAC，全部在浏览器本地完成。" :tags="['Hash','HMAC']"/><section class="tool-box sr-panel"><label class="sr-tool-label">输入文本</label><textarea v-model="input" placeholder="输入需要计算的文本"></textarea><div class="settings"><el-select v-model="algorithm"><el-option label="MD5" value="md5"/><el-option label="SHA-1" value="sha1"/><el-option label="SHA-256" value="sha256"/><el-option label="SHA-512" value="sha512"/></el-select><el-switch v-model="useHmac" active-text="使用 HMAC"/><el-input v-if="useHmac" v-model="key" type="password" show-password placeholder="HMAC 密钥"/></div><div class="actions"><el-button class="sr-primary-button" type="primary" @click="run">开始计算</el-button><el-button :disabled="!output" @click="copy">复制结果</el-button><el-button @click="input='';output='';error=''">清空</el-button></div><p v-if="error" class="error">{{error}}</p></section><section v-if="output" class="result sr-panel"><h2>计算结果</h2><code>{{output}}</code></section><ToolDocumentation :sections="docs"/></div></template>
<style scoped lang="scss">.tool-box,.result{padding:20px}.tool-box>textarea{display:block;width:100%;height:220px;margin-top:9px;padding:14px;border:1px solid var(--sr-border);border-radius:var(--sr-radius-control);resize:vertical;background:var(--sr-surface-soft);color:var(--sr-text);font:14px/1.65 ui-monospace,monospace}.settings{display:flex;align-items:center;gap:12px;margin-top:14px}.settings .el-select{width:160px}.settings .el-input{max-width:360px}.actions{display:flex;gap:8px;margin-top:14px}.error{color:#c43f3f}.result{margin-top:14px}.result h2{margin:0 0 12px;color:#218a5a;font-size:15px}.result code{word-break:break-all}</style>
