<script setup lang="ts">
import { ref } from 'vue'; import { ElMessage } from 'element-plus'; import ToolPageHeader from '@/components/tool/ToolPageHeader.vue'; import ToolDocumentation from '@/components/tool/ToolDocumentation.vue'; import { encodeUrl, decodeUrl, type UrlMode } from '../lib/urlCodec'
const input=ref(''); const output=ref(''); const mode=ref<UrlMode>('component'); const error=ref('')
function transform(action:'encode'|'decode'){try{error.value='';output.value=action==='encode'?encodeUrl(input.value,mode.value):decodeUrl(input.value,mode.value)}catch(e){error.value=e instanceof Error?`处理失败：${e.message}`:'处理失败，请检查输入'}}
function swap(){[input.value,output.value]=[output.value,input.value]}
async function copy(){await navigator.clipboard.writeText(output.value);ElMessage.success('结果已复制')}
const docs=[{title:'两种模式的区别',content:'完整 URL 模式保留 : / ? # 等结构字符；组件模式会编码这些字符，适合查询参数值。'},{title:'何时使用编码',content:'URL 中出现汉字、空格或特殊符号时需要编码。不要对已经编码的内容重复编码。'},{title:'错误说明',content:'解码输入中的百分号必须跟随两个十六进制字符，例如 %E4；非法序列会明确提示失败。'}]
</script>
<template><div class="sr-page"><ToolPageHeader category="编码转换" title="URL 编解码" description="编码或还原完整 URL、查询参数及普通文本。" :tags="['URL','编码']"/><section class="codec sr-panel"><div class="toolbar"><el-radio-group v-model="mode"><el-radio-button value="uri">完整 URL</el-radio-button><el-radio-button value="component">URL 组件</el-radio-button></el-radio-group><el-button @click="swap">交换内容</el-button><el-button @click="input='';output='';error=''">清空</el-button></div><div class="columns"><label class="sr-tool-label">输入<textarea v-model="input" placeholder="输入需要处理的 URL 或文本"></textarea></label><label class="sr-tool-label">结果<textarea v-model="output" readonly placeholder="结果将在这里显示"></textarea></label></div><p v-if="error" class="error">{{ error }}</p><div class="actions"><el-button class="sr-primary-button" type="primary" @click="transform('encode')">编码</el-button><el-button class="sr-primary-button" type="primary" @click="transform('decode')">解码</el-button><el-button :disabled="!output" @click="copy">复制结果</el-button></div></section><ToolDocumentation :sections="docs"/></div></template>
<style scoped lang="scss">.codec{padding:20px}.toolbar{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:16px}.columns{display:grid;grid-template-columns:1fr 1fr;gap:14px}label{color:var(--sr-text-muted);font-size:13px;font-weight:600}textarea{display:block;width:100%;height:260px;margin-top:8px;padding:14px;border:1px solid var(--sr-border);border-radius:var(--sr-radius-control);outline:0;resize:vertical;background:var(--sr-surface-soft);color:var(--sr-text);font:13px/1.65 ui-monospace,monospace}textarea:focus{border-color:var(--sr-blue)}.actions{display:flex;gap:8px;margin-top:16px}.error{color:#d34b4b;font-size:13px}@media(max-width:720px){.columns{grid-template-columns:1fr}}</style>
