<script setup lang="ts">
import { ref } from 'vue'; import { ElMessage } from 'element-plus'; import ToolPageHeader from '@/components/tool/ToolPageHeader.vue'; import ToolDocumentation from '@/components/tool/ToolDocumentation.vue'; import { decodeBase64, encodeBase64 } from '../lib/base64'
const input=ref('');const output=ref('');const error=ref('')
function run(mode:'encode'|'decode'){try{error.value='';output.value=mode==='encode'?encodeBase64(input.value):decodeBase64(input.value)}catch(e){output.value='';error.value=e instanceof Error?e.message:'处理失败'}}
function swap(){[input.value,output.value]=[output.value,input.value]}
async function copy(){await navigator.clipboard.writeText(output.value);ElMessage.success('结果已复制')}
const docs=[{title:'Unicode 支持',content:'文本先按 UTF-8 编码，因此中文、Emoji 和其他 Unicode 字符可以正确往返。'},{title:'隐私',content:'编码和解码全部在当前浏览器完成，内容不会上传。'}]
</script>
<template><div class="sr-page"><ToolPageHeader category="编码转换" title="Base64 编解码" description="使用 UTF-8 在普通文本与 Base64 之间转换。" :tags="['Base64','UTF-8']"/><section class="tool-box sr-panel"><div class="columns"><label class="sr-tool-label">输入<textarea v-model="input" placeholder="输入文本或 Base64"></textarea></label><label class="sr-tool-label">结果<textarea v-model="output" readonly placeholder="结果将在这里显示"></textarea></label></div><p v-if="error" class="error">{{error}}</p><div class="actions"><el-button class="sr-primary-button" type="primary" @click="run('encode')">编码</el-button><el-button class="sr-primary-button" type="primary" @click="run('decode')">解码</el-button><el-button @click="swap">交换内容</el-button><el-button :disabled="!output" @click="copy">复制结果</el-button><el-button @click="input='';output='';error=''">清空</el-button></div></section><ToolDocumentation :sections="docs"/></div></template>
<style scoped lang="scss">.tool-box{padding:20px}.columns{display:grid;grid-template-columns:1fr 1fr;gap:14px}textarea{display:block;width:100%;height:300px;margin-top:9px;padding:14px;border:1px solid var(--sr-border);border-radius:var(--sr-radius-control);resize:vertical;background:var(--sr-surface-soft);color:var(--sr-text);font:14px/1.65 ui-monospace,monospace}textarea:focus{outline:0;border-color:var(--sr-blue)}.actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}.error{color:#c43f3f}@media(max-width:720px){.columns{grid-template-columns:1fr}}</style>
